/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ImpoundsIndexRouteImport } from './routes/impounds.index'
import { Route as ImpoundsRegisterRouteImport } from './routes/impounds.register'
import { Route as ImpoundsReleaseRouteImport } from './routes/impounds.release'
import { Route as VehiclesSearchRouteImport } from './routes/vehicles.search'
import { Route as ViolationsIndexRouteImport } from './routes/violations.index'
import { Route as ViolationsAddRouteImport } from './routes/violations.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpoundsIndexRoute = ImpoundsIndexRouteImport.update({
  id: '/impounds/',
  path: '/impounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpoundsRegisterRoute = ImpoundsRegisterRouteImport.update({
  id: '/impounds/register',
  path: '/impounds/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpoundsReleaseRoute = ImpoundsReleaseRouteImport.update({
  id: '/impounds/release',
  path: '/impounds/release',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesSearchRoute = VehiclesSearchRouteImport.update({
  id: '/vehicles/search',
  path: '/vehicles/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsIndexRoute = ViolationsIndexRouteImport.update({
  id: '/violations/',
  path: '/violations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsAddRoute = ViolationsAddRouteImport.update({
  id: '/violations/add',
  path: '/violations/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/impounds/register': typeof ImpoundsRegisterRoute
  '/impounds/release': typeof ImpoundsReleaseRoute
  '/vehicles/search': typeof VehiclesSearchRoute
  '/violations/add': typeof ViolationsAddRoute
  '/impounds/': typeof ImpoundsIndexRoute
  '/violations/': typeof ViolationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/impounds/register': typeof ImpoundsRegisterRoute
  '/impounds/release': typeof ImpoundsReleaseRoute
  '/vehicles/search': typeof VehiclesSearchRoute
  '/violations/add': typeof ViolationsAddRoute
  '/impounds': typeof ImpoundsIndexRoute
  '/violations': typeof ViolationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/impounds/register': typeof ImpoundsRegisterRoute
  '/impounds/release': typeof ImpoundsReleaseRoute
  '/vehicles/search': typeof VehiclesSearchRoute
  '/violations/add': typeof ViolationsAddRoute
  '/impounds/': typeof ImpoundsIndexRoute
  '/violations/': typeof ViolationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/settings'
    | '/impounds/register'
    | '/impounds/release'
    | '/vehicles/search'
    | '/violations/add'
    | '/impounds/'
    | '/violations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Login'
    | '/settings'
    | '/impounds/register'
    | '/impounds/release'
    | '/vehicles/search'
    | '/violations/add'
    | '/impounds'
    | '/violations'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/settings'
    | '/impounds/register'
    | '/impounds/release'
    | '/vehicles/search'
    | '/violations/add'
    | '/impounds/'
    | '/violations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ImpoundsRegisterRoute: typeof ImpoundsRegisterRoute
  ImpoundsReleaseRoute: typeof ImpoundsReleaseRoute
  VehiclesSearchRoute: typeof VehiclesSearchRoute
  ViolationsAddRoute: typeof ViolationsAddRoute
  ImpoundsIndexRoute: typeof ImpoundsIndexRoute
  ViolationsIndexRoute: typeof ViolationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impounds/': {
      id: '/impounds/'
      path: '/impounds'
      fullPath: '/impounds/'
      preLoaderRoute: typeof ImpoundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impounds/register': {
      id: '/impounds/register'
      path: '/impounds/register'
      fullPath: '/impounds/register'
      preLoaderRoute: typeof ImpoundsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impounds/release': {
      id: '/impounds/release'
      path: '/impounds/release'
      fullPath: '/impounds/release'
      preLoaderRoute: typeof ImpoundsReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/search': {
      id: '/vehicles/search'
      path: '/vehicles/search'
      fullPath: '/vehicles/search'
      preLoaderRoute: typeof VehiclesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations/': {
      id: '/violations/'
      path: '/violations'
      fullPath: '/violations/'
      preLoaderRoute: typeof ViolationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations/add': {
      id: '/violations/add'
      path: '/violations/add'
      fullPath: '/violations/add'
      preLoaderRoute: typeof ViolationsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ImpoundsRegisterRoute: ImpoundsRegisterRoute,
  ImpoundsReleaseRoute: ImpoundsReleaseRoute,
  VehiclesSearchRoute: VehiclesSearchRoute,
  ViolationsAddRoute: ViolationsAddRoute,
  ImpoundsIndexRoute: ImpoundsIndexRoute,
  ViolationsIndexRoute: ViolationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
